# This file could be used for testing the API with Visual Studio Code

## Execute Log In
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "enrico@gmail.com",
    "password": "pass"
}
###

## Checking if user is still logged-in.
GET http://localhost:3001/api/sessions/current HTTP/1.1
###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
###

## Get All The Authors
GET http://localhost:3001/api/authors HTTP/1.1
###

## Get all the pages for the frontoffice visualization.
GET http://localhost:3001/api/pages/frontoffice HTTP/1.1
###

## Get all the pages for the backoffice visualization.
GET http://localhost:3001/api/pages/backoffice HTTP/1.1
###

## Get a specific only-published page (front office), identified by the id <id>, along with the associated blocks.
GET http://localhost:3001/api/pages/frontoffice/1 HTTP/1.1
###

## Get a specific page (back office), identified by the id <id>, along with the associated blocks.
GET http://localhost:3001/api/pages/backoffice/5 HTTP/1.1
###

## Create a new Page, along with the associated blocks.
POST http://localhost:3001/api/pages HTTP/1.1
content-type: application/json

{
  "userId" : 1,
  "title": "Nuova Pagina",
  "creationDate": "2023-02-28",
  "publicationDate": "2023-02-28",
  "blocks": [
    {
      "type": "Header",
      "content": "Nuovo",
      "blockOrder": 1
    },
    {
      "type": "Image",
      "content": "imag1.jpg",
      "blockOrder": 2
    },
    {
      "type": "Image",
      "content": "imge1.jpg",
      "blockOrder": 3
    }
  ]
}
###

## Updates the page.
POST http://localhost:3001/api/pages/1 HTTP/1.1
content-type: application/json

{
  "id": 1,
  "userId" : 1,
  "title": "pages1",
  "creationDate": "2023-02-28",
  "blocks": [
    {
      "pageId": 1,
      "type": "Header",
      "content": "Blog",
      "blockOrder": 1
    },
    {
      "pageId": 1,
      "type": "Image",
      "content": "iage1.jpg",
      "blockOrder": 2
    },
    {
      "pageId": 1,
      "type": "Image",
      "content": "imae1.jpg",
      "blockOrder": 3
    }
  ]
}

###

# Delete the page.
DELETE http://localhost:3001/api/pages/2 HTTP/1.1
###

## Get the website name.
GET http://localhost:3001/api/websites HTTP/1.1
###

## Update the website name.
PUT http://localhost:3001/api/websites/nuovoNome HTTP/1.1
###

## Get all the images relative path
GET http://localhost:3001/api/images HTTP/1.1
###